server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    # 向注册中心注册自己
    register-with-eureka: true
    # 需要服务发现功能
    fetch-registry: true
    # 是一个Map<String, String>，defaultZone可以指定交互的地址查询服务和注册服务的地址
    service-url:
      # 通过这个地址与注册中心保存连接与注册
      defaultZone: http://eureka1.fq.com:7001/eureka,http://eureka2.fq.com:7002/eureka