server:
  port: 7001

eureka:
  instance:
    hostname: eureka1.fq.com # eureka服务端的实例名称

  client:
    # 是否将自己注册到注册中心
    register-with-eureka: false
    # 是否是否需要去检索服务，由于当前是注册中心，不需要去服务发现与调用
    fetch-registry: false
    # 是一个Map<String, String>，defaultZone可以指定交互的地址查询服务和注册服务的地址
    service-url:
      # 集群：注册到7002
      # defaultZone: http://eureka2.fq.com:7002/eureka/
      # 单机：注册到7001（自己）
      defaultZone: http://eureka1.fq.com:7001/eureka/
  server:
    # 关闭自我保留机制
    enable-self-preservation: false
    # 心跳间隔时间
    eviction-interval-timer-in-ms: 2000